### ISSUE TITLE
Rate-limiting approach insufficient for multi-threaded contexts

### ISSUE THREAD

**Issue by Majored** [swanis/mcmarket-api-java-wrapper#1]
Heya Swanis,

Thanks for all your work with this wrapper. When initially going through your wrapper during the API beta, I noticed two things in relation to rate limiting but did not see a need to correct them at that stage due to the closed nature of the beta. Now that we've migrated and released the API, I'd like to suggest two changes. 

At current, it seems a request is sent and if a rate limit error is returned, you delay for the appropriate amount of time and then re-send the request. This approach is perfect for a single-threaded context as the delay blocks the thread, and prevents any other requests from sneaking in-between. However, this would not be the case in multi-threaded contexts.

Instead, it would be worth using the approach seen in the official wrapper (or any of my personal wrappers) where you store the retry delay and last request date in the Client object. Each time a request is received, you check whether you're still in a rate-limited period and pre-emptively delay, preventing you from sending a request whilst you still know you're rate limited. Every time you get rate limited, you update that store. Every time you get any response code that isn't 429, you know you aren't rate-limited and can reset the store.

Further, the rate limits applied to READ operations (ie. GETs) are independent of WRITE operations (ie. POST/PATCH/DELETE), so it would be worth storing a retry delay and the last request time for both types (and check those appropriately). There could be a situation where one thread makes a GET, another makes a POST, and a request is made whilst still rate-limited (or vice versa).

I'll leave this as an issue for the moment but if you'd like me to make this addition when I have a moment and submit a PR, let me know.

Thanks,
Harry

**Comment by swanis** [comment]
Hello,

Feel free to implement these changes yourself if you'd like. 
I have yet to receive the Ultimate upgrade which was promised in the conversation, and can therefore not debug this wrapper any more.
